public enum TokenType {
    KEYWORD,
    IDENTIFIER,
    INTEGER_LITERAL,
    FLOAT_LITERAL,
    STRING_LITERAL,
    CHARACTER_LITERAL,
    BOOLEAN_LITERAL,
    OPERATOR,
    PUNCTUATOR,
    COMMENT,
    WHITESPACE,
    EOF,
    ERROR
}
